# Generated by Django 3.2.9 on 2021-12-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szermierka', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uczeń',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='imie',
            new_name='name',
        ),
    ]
