# Generated by Django 3.2.9 on 2021-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szermierka', '0002_auto_20211204_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=64, unique=True)),
                ('rok', models.PositiveSmallIntegerField(default=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
