# Generated by Django 3.2.9 on 2021-12-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szermierka', '0007_auto_20211210_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (0, 'Inne'), (3, 'Sci-Fi'), (2, 'Komedia'), (1, 'Horror')], default=0),
        ),
    ]
